# Use a specific Node.js LTS version for stability
FROM node:18

# Set the working directory
WORKDIR /app

# Expose the port for the service
ENV PORT 8080

# Copy necessary files into the container
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install

# Copy the rest of the application files
COPY . .

# Expose the port Cloud Run will use
EXPOSE 8080

# Run the application
CMD [ "yarn", "start" ]
